NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200 
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 3
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 1
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 24

NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_COOLDOWN_DURATION = 9000
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 9
NDefines.NCountry.RAZE_PROVINCE_POWER_PER_DEVELOPMENT = 10.0

NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0

NDefines.NAI.MIN_SCORE_TO_CONCENTRATE_DEVELOPMENT = 100

NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20

NDefines.NReligion.CONVERSION_ZEAL_DURATION = 3650

NDefines.NGame.DAYS_BEHIND_PAUSE = 90
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 33